### ISSUE TITLE
[Ruby 2.3] Thread.exclusive is deprecated, use Mutex

### ISSUE THREAD

**Issue by emerleite** [karlfreeman/multi_mime#5]
It's a deprecations warning. I guess we should change it, makes sense?

```
Thread.exclusive is deprecated, use Mutex
/home/application/current/vendor/bundle/ruby/2.3.0/gems/multi_mime-1.0.1/lib/multi_mime.rb:49:in `use'
/home/application/current/vendor/bundle/ruby/2.3.0/gems/multi_mime-1.0.1/lib/multi_mime.rb:37:in `adapter'
/home/application/current/vendor/bundle/ruby/2.3.0/gems/multi_mime-1.0.1/lib/multi_mime.rb:118:in `current_adapter'
/home/application/current/vendor/bundle/ruby/2.3.0/gems/multi_mime-1.0.1/lib/multi_mime.rb:107:in `type_for_file'
```

**Comment by karlfreeman** [comment]
I've cut a [new gem](https://rubygems.org/gems/multi_mime/versions/1.1.0) solving this. Any problems let me know 👍.
